---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.132.95
      ansible_user: ansible
      ansible_ssh_private_key_file: "/home/myash/.ssh/id_rsa"
vector:
  hosts:
    vector:
      ansible_host: 158.160.178.90
      ansible_user: ansible
      ansible_ssh_private_key_file: "/home/myash/.ssh/id_rsa"
lighthouse:
  hosts:
   lighthouse:
      ansible_host: 158.160.185.226
      ansible_user: ansible
      ansible_ssh_private_key_file: "/home/myash/.ssh/id_rsa"

